version: '3.9'

networks:
    app-net:
        ipam:
            driver: 'default'

volumes:
    redis-datastore:
    rabbitmq-datastore:
    db-datastore:

services:
#    redis:
#        image: redis:alpine3.14
#        volumes:
#            - 'redis-datastore:/bitnami/redis/data'
#        networks:
#            - 'app-net'
#        ports:
#            - '6379:6379'

#    rabbitmq:
#        image: rabbitmq:3-management-alpine
#        volumes:
#            - 'rabbitmq-datastore:/var/lib/rabbitmq'
#        networks:
#            - 'app-net'
#        ports:
#            - '5672:5672'
#            - '15672:15672'

    db:
        image: 'dap/mysql:8.0'
        command:
            - 'mysqld'
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
        volumes:
            - 'db-datastore:/var/lib/mysql'
        networks:
            - 'app-net'
        ports:
            - '3306:3306'
        security_opt:
            - 'seccomp:unconfined'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'gpx'

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: developer
        volumes:
            - './:/app'
        depends_on:
            - 'db'
        networks:
            - 'app-net'
        ports:
            - "80:80"
        environment:
            DATABASE_URL: "mysql://root:root@db:3306/gpx?serverVersion=8.0"
