services:
    App\Manager\_Manager_:
        abstract: true
        public: false
        tags: [ 'manager' ]

    app.manager.estructura:
        class: App\Manager\EstructuraManager
        parent: App\Manager\_Manager_
        public: true
        tags: [ 'manager' ]

    app.manager.persona:
        parent: App\Manager\_Manager_
        class: App\Manager\PersonaManager
        public: true

    app.manager.route:
        parent: App\Manager\_Manager_
        class: App\Manager\RouteManager
        public: true
        calls:
            - setRoute: [ '@router' ]

    app.manager.fixture:
        class: App\Manager\FixtureManager
        parent: App\Manager\_Manager_
        arguments: [ '%kernel.project_dir%/src/Config/Fixtures' ]
        public: true

    app.manager.envio_manifiesto:
        class: App\Manager\EnvioManifiestoManager
        parent: App\Manager\_Manager_
        public: true

    app.manager.curl_conection:
        class: App\Manager\CurlConectionManager
        parent: App\Manager\_Manager_
        public: true
        arguments: [ '@doctrine.orm.default_entity_manager' ]

    app.manager.envio:
        class: App\Manager\EnvioManager
        parent: App\Manager\_Manager_
        public: true
        arguments: [ '@doctrine.orm.default_entity_manager' ]