services:
    App\Menu\_Menu_:
        abstract: true
        calls:
            -   setFactory: [ '@knp_menu.factory' ]
            -   setEntityManager: [ '@Doctrine\ORM\EntityManagerInterface' ]
            -   setRequestStack: [ '@request_stack' ]
            -   setStorage: [ '@security.token_storage' ]

    app.menu_builder:
        class: App\Menu\MenuBuilder
        parent: App\Menu\_Menu_

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: [ "@app.menu_builder", createMainMenu ]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
