services:
#    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
#        arguments:
#            - '%env(DATABASE_URL)%'
#            - { db_table: 'trabajador_credencial', db_id_col: 'session' }
