services:
    App\Security\Voter\RouteAccessVoter:
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - 'security.voter'

    app.service.notify:
        class: App\Service\NotifyService
        public: true
        arguments:
          [ '@Symfony\Component\HttpFoundation\Session\SessionInterface' ]