services:
#    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
#        arguments:
#            - '%env(DATABASE_URL)%'
#            - { db_table: 'trabajador_credencial', db_id_col: 'session' }
    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createMainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
